image: joyzoursky/python-chromedriver:3.7-selenium

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

stages:
    - coverage_report
    - busca_trades
    - relatorio

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt 

coverage_html:
    stage: coverage_report
    script:
        - python coverage_test.py
        - mkdir -p public/coverage_report
        - mv coverage_report public/coverage_report
    artifacts:
        paths:
            - public
        expire_in: 15 days

busca_trades:
    stage: busca_trades
    script:
        - python ./ir.py --do busca_trades
    artifacts:
        paths:
            - public
        expire_in: 15 days

relatorio:
    stage: relatorio
    script:
        - python ./ir.py --do custodia
        - python ./ir.py --do vendas_no_mes